version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-lithium
    container_name: selenium-hub
    restart: always
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-lithium
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.141.59-lithium
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
